### ISSUE TITLE
Describe the structure of the configuration file

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/data-analyses-scheduler#12]

**Comment by Cerfoglg** [comment]
@VincenzoFerme 

The scheduler takes 3 files for configuration.

The first file is the configuration of the scheduler itself, which is a YML file containing settings for the scheduler. These can be overwritten via environment variables. The settings by default are currently:

```
cassandra_keyspace: "benchflow"
kafka_host: "kafka"
kafka_port: "2181"
cassandra_host: "cassandra"
minio_host: "minio"
minio_port: "9000"
minio_ssl: true
minio_access_key: "AKIAIOSFODNN7EXAMPLE"
minio_secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
runs_bucket: "runs"
driver_memory: "8g"
executor_memory: "8g"
executor_heartbeat_interval: "300000s"
block_manager_slave_timeout_ms: "300000s"
ack_wait_timeout: "300000s"
spark_home: "/usr/spark"
spark_master: "local[*]"
spark_port: "7077"
alluxio_port: "19998"
pyspark_cassandra_version: "0.3.5"
app_path: "/app"
analysers_path: "analysers"
transformers_path: "data-transformers"
transformers_configurations_path: "data-transformers/suts"
transformers_configuration_file_name: "data-transformers.configuration.yml"
analysers_configurations_path: "analysers/suts"
analysers_configuration_file_name: "analysers.configuration.yml"
tests_config_bucket: "tests"
tests_config_name: "benchflow-test.yml"
transformer_workers: 4
analyser_workers: 4
```

The other two files are the configurations of the dependencies for the scripts to submit to Spark.  An example of the transformers configuration:

```
transformers_settings: 
    - topic: "stats"
      scripts: 
        - script: "data-transformers/transformers/statsTransformer.py"
    - topic: "mysql"
      scripts: 
        - script: "data-transformers/transformers/mysqlTransformer.py"
    - topic: "properties"
      scripts: 
        - script: "data-transformers/transformers/propertiesTransformer.py"
    - topic: "faban"
      scripts: 
        - script: "data-transformers/transformers/fabanTransformer.py"
```

Written as a YAML file as well, the transformer_settings field contains a list of entries, each containing the topic to listen for mesages on Kafka, and the script to launch for transforming the data.

An example of the analysers configuration is as follows:

```
analysers_settings: 
    - requirements: "faban"
      scripts: 
        - script_name: "faban_analyser"
          script_trial: "analysers/trials/faban.py"
          script_experiment: "analysers/experiments/faban.py"
    - requirements: "stats,properties"
      scripts: 
        - script_name: "ram"
          script_trial: "analysers/trials/ram.py"
          script_experiment: "analysers/experiments/ram.py"
        - script_name: "cpu"
          script_trial: "analysers/trials/cpu.py"
          script_experiment: "analysers/experiments/cpu.py"
        - script_name: "io"
          script_trial: "analysers/trials/IO.py"
          script_experiment: "analysers/experiments/IO.py"
    - requirements: "mysql"
      scripts: 
        - script_name: "execution_time"
          script_trial: "analysers/trials/executionTime.py"
          script_experiment: "analysers/experiments/executionTime.py"
        - script_name: "process_duration"
          script_trial: "analysers/trials/processDuration.py"
          script_experiment: "analysers/experiments/processDuration.py"
        - script_name: "number_of_process_instances"
          script_trial: "analysers/trials/numberOfProcessInstances.py"
          script_experiment: "analysers/experiments/numberOfProcessInstances.py"
        - script_name: "construct_duration"
          script_trial: "analysers/trials/constructDuration.py"
          script_experiment: "analysers/experiments/constructDuration.py"
        - script_name: "number_of_construct_instances"
          script_trial: "analysers/trials/numberOfConstructInstances.py"
          script_experiment: "analysers/experiments/numberOfConstructInstances.py"
        - script_name: "database_size"
          script_trial: "analysers/trials/databaseSize.py"
          script_experiment: "analysers/experiments/databaseSize.py"
    - requirements: "number_of_process_instances,execution_time"
      scripts: 
        - script_name: "throughput"
          script_trial: "analysers/trials/throughput.py"
          script_experiment: "analysers/experiments/throughput.py"
```

Where analysers_settings defines a list of requirements, each requirement written as a coma separated list (no spaces), and for each requirements we define the scripts to launch when those are met, where each script defines the name for the script, the path of the trial script, and the path of the experiment script. Requirements can be defined using the script names, as well as names of the topics for the transformer scripts.
